config/routes.rb
Rails.application.routes.draw do


  get 'users/:id/show' => "users#show"
  post 'comments/:id/create' => "comments#create"
  post 'comments/:id/destroy' => "comments#destroy"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :charges
  resources :agreements, :only => [:create]
  resources :messages, :only => [:create, :destroy]
  resources :rooms, :only => [:create, :destroy, :show]
  
  get '/' => "home#top"
  get '/about' => "home#about"
  get '/terms' => "home#terms"
  get '/privacy' => "home#privacy"
  get '/flow' => "home#flow"
  get '/ctl' => "home#ctl"
  get '/contact' => "home#contact"
  get '/signup' => "home#signup"
  get '/mypage' => "home#mypage"


  get 'movies/index' => "movies#index"
  get 'movies/:id/show' => "movies#show"
  get 'movies/wedding_more' => "movies#wedding_more"
  get 'movies/travel_more' => "movies#travel_more"
  get 'movies/anniversary_more' => "movies#anniversary_more"
  get 'movies/other_more' => "movies#other_more"
  get 'movies/new' => "movies#new"
  get 'movies/:id/new' => "movies#new2"
  post 'movies/create' => "movies#create"

  get 'pilots/index' => "pilots#index"
  get 'pilots/:id/show' => "pilots#show"
  get 'pilots/offer' => "pilots#offer"
  get 'pilots/reservation' => "pilots#reservation"
  get 'pilots/ace_more' => "pilots#ace_more"
  get 'pilots/pro_more' => "pilots#pro_more"
  get 'pilots/amature_more' => "pilots#amature_more"
  get 'pilots/new' => "pilots#new"
  post 'pilots/create' => "pilots#create"
  
  get 'agreements/:id/new' => "agreements#new"  
  get 'agreements/:id/show' => "agreements#show"
  post 'agreements/:id/agree' => "agreements#agree"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.order(created_at: :desc)
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to("/mypage")
      flash[:notice] = "交渉を中断しました"
    end
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<main>
  <div class="heading room">
    <div class="container">
      <div class="dm-header text-center">
        <h2 class="mx-auto mb-5">ダイレクトメッセージ</h2>
        <h4 class="mb-3">参加者</h4>
        <% @entries.each do |e| %>
          <h5><strong><%= e.user.name%>さん</strong></h5>
        <% end %>
        <% if current_user.pilot_flg == true %>
        <% @entries.each do |e| %>
          <% if e.user_id != @current_user.id %>
            <%= link_to("契約を確定する", "/agreements/#{e.user_id}/new", class: "btn btn-danger", data:{ confirm: "契約の確定に進みます" }) %>
          <% end %>
        <% end %>
          <%= link_to("交渉を中断する", room_path(), method: :delete , class: "btn btn-warning", data:{ confirm: "本当に交渉を中断しますか？" }) %>
        <% else %>
          <%= link_to("交渉を中断する", room_path(), method: :delete , class: "btn btn-warning", data:{ confirm: "本当に交渉を中断しますか？" }) %>
        <% end %>
        <p class="mt-5">※　日程・金額・撮影場所・撮影へのこだわりなどをご相談の上、契約を確定させてください。<br>契約の確定前に本サービス上で直接連絡先を交換する行為は規約により禁止されております。</p>
      </div>
      
      <div class="dm-contents">
        <div class="dm-form text-center">
        <%= form_for @message do |f| %>
          <%= f.text_area :content, :placeholder => "メッセージを入力して下さい" , :size => "70*50" , :maxlength => "70" %>
          <%= f.hidden_field :room_id, :value => @room.id %>
          <br>
          <br>
          <%= f.submit "送信", :class=>"btn btn-primary" %>
        <% end %>
        </div>
        <hr>
        <% if @messages.present? %>
          <% @messages.each do |m| %>
            <strong><%= simple_format(m.content) %></strong>
            <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></strong></small>
            <hr>
          <% end %>
        <% else %>
          <h3 class="text-center">メッセージはまだありません</h3>
        <% end %>
      </div>
    </div>
  </div>
</main>