config/routes.rb
Rails.application.routes.draw do


  get 'users/:id/show' => "users#show"
  post 'comments/:id/create' => "comments#create"
  post 'comments/:id/destroy' => "comments#destroy"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :charges
  resources :agreements, :only => [:create]
  resources :messages, :only => [:create, :destroy]
  resources :rooms, :only => [:create, :destroy, :show]
  
  get '/' => "home#top"
  get '/about' => "home#about"
  get '/terms' => "home#terms"
  get '/privacy' => "home#privacy"
  get '/flow' => "home#flow"
  get '/ctl' => "home#ctl"
  get '/contact' => "home#contact"
  get '/signup' => "home#signup"
  get '/mypage' => "home#mypage"


  get 'movies/index' => "movies#index"
  get 'movies/:id/show' => "movies#show"
  get 'movies/wedding_more' => "movies#wedding_more"
  get 'movies/travel_more' => "movies#travel_more"
  get 'movies/anniversary_more' => "movies#anniversary_more"
  get 'movies/other_more' => "movies#other_more"
  get 'movies/new' => "movies#new"
  get 'movies/:id/new' => "movies#new2"
  post 'movies/create' => "movies#create"

  get 'pilots/index' => "pilots#index"
  get 'pilots/:id/show' => "pilots#show"
  get 'pilots/offer' => "pilots#offer"
  get 'pilots/reservation' => "pilots#reservation"
  get 'pilots/ace_more' => "pilots#ace_more"
  get 'pilots/pro_more' => "pilots#pro_more"
  get 'pilots/amature_more' => "pilots#amature_more"
  get 'pilots/new' => "pilots#new"
  post 'pilots/create' => "pilots#create"
  
  get 'agreements/:id/new' => "agreements#new"  
  get 'agreements/:id/show' => "agreements#show"
  post 'agreements/:id/agree' => "agreements#agree"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    elsif user
      can :read, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/agreement.rb
class Agreement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title,{presence: true}
  validates :user_id,{presence: true}
  validates :pilot_id,{presence: true}
  validates :url,{presence: true}
  validates :tag,{presence: true}
  belongs_to :user
  belongs_to :pilot
  has_many :comments
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  validates :user_id,{presence: true, uniqueness: true}
  validates :name,{presence: true}
  validates :rank,{presence: true}
  validates :adress,{presence: true}
  validates :skill,{presence: true}
  validates :tools,{presence: true}
  validates :price,{presence: true}
  validates :insuarance,{presence: true}
  validates :message,{presence: true}
  belongs_to :user
  has_many :movies
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :pilots, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :agreements, dependent: :destroy
  include Gravtastic
    gravtastic
end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  
  def new
    @user = User.find_by(id: params[:id])
  end
  
  def create
    @receiver = User.find_by(id: params[:user_id])
    @agreement = Agreement.new(user_id: params[:user_id], pilot_id: current_user.id, price: params[:price], date: params[:date], due_date: params[:due_date], place: params[:place], contact: params[:contact], other: params[:other])
    if @agreement.save
      UserMailer.agreement_mail(@receiver,@agreement).deliver_now
      flash[:notice] = "契約を確定しました"
      redirect_to("/mypage")
    else
    end
  end
  
  def show
    @agreement = Agreement.find_by(id: params[:id])
    @user = User.find_by(id: @agreement.user_id)
    @pilot = Pilot.find_by(user_id: @agreement.pilot_id)
  end
  
  def agree
    @agreement = Agreement.find_by(id: params[:id])
    @receiver = User.find_by(id: @agreement.pilot_id)
    if @agreement.update_attribute(:agreement_flag, true)
      UserMailer.agree_mail(@receiver,@agreement).deliver_now
      flash[:notice] = "契約を確定しました"
      redirect_to("/mypage")
    else
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
  def terms
  end
  def privacy
  end
  def ctl
  end
  def flow
  end
  def contact
  end
  def mypage
    @entries = Entry.where(user: current_user.id)
    @agreements_u = Agreement.where(user_id: current_user.id)
    @agreements_p = Agreement.where(pilot_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.order(created_at: :desc)
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to("/mypage")
      flash[:notice] = "交渉を中断しました"
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agreements/new.html.erb
<main>
  <div class="heading agreements-new">
    <div class="container">
      <h2 class="form-heading text-center mx-auto">契約内容の確定</h2>
      <div class="form agreements-form text-center">
        <div class="form-body">
          <%= form_tag agreements_path do %>
            <p>依頼者名</p>
            <h5><%= @user.name %></h5>
            <%= hidden_field_tag :user_id, @user.id %>
            <p>金額（円）</p>
            <input name="price" type="number" required></input>
            <p>撮影予定日</p>
            <input name="date" type="date" required></input>
            <p>納品予定日</p>
            <input name="due_date" type="date" required></input>
            <p>撮影地</p>
            <input name="place" type="text" required></input>
            <p>連絡用メールアドレス</p>
            <input name="contact" type="email" required></input>
            <p>その他特記事項</p>
            <textarea name="other"></textarea>
            <input class="btn btn-primary" type="submit" value="契約内容の確定">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/agreements/show.html.erb
<main>
  <div class="heading agreements-show">
    <div class="container">
      <h2 class="agreements-heading text-center mx-auto">契約内容の確認</h2>
      <div class="agreements-contents mx-auto">
        <dl>
          <dt>依頼者 :</dt>
          <dd><%= @user.name %></dd>
          <div class="clear"></div>
          <dt>パイロット :</dt>
          <dd><%= @pilot.name %></dd>
          <div class="clear"></div>
          <dt>金額 :</dt>
          <dd>¥<%= @agreement.price %></dd>
          <div class="clear"></div>
          <dt>撮影予定日 :</dt>
          <dd><%= @agreement.date.strftime(" %Y年 %m月 %d日") %></dd>
          <div class="clear"></div>
          <dt>納品予定日 :</dt>
          <dd><%= @agreement.due_date.strftime(" %Y年 %m月 %d日") %></dd>
          <div class="clear"></div>
          <dt>撮影地 : </dt>
          <dd><%= @agreement.place %></dd>
          <div class="clear"></div>
          <dt>メッセージ : </dt>
          <dd><%= @agreement.other %></dd>
          <div class="clear"></div>
          <dt>連絡先 :</dt>
          <dd><%= @agreement.contact %></dd>
          <div class="clear"></div>
          <dt>契約の確定状況 :</dt>
          <% if @agreement.agreement_flag == true %>
            <dd>確定済み</dd>
          <% else %>
            <dd style="color: red">未確定</dd>
          <% end %>
          </dd>
          <div class="clear"></div>
          <%= form_tag("/agreements/#{@agreement.id}/agree", method: :post) do %>
            <% if @agreement.agreement_flag != true && @agreement.user_id == current_user.id %>
              <div class="confirm mx-auto text-center">
                <div class="checkbox  mt-5 ml-5">
                  <input type="checkbox" required></input><span><a href="/terms">利用規約</a>を確認しました。</span>
                </div>
                <input class="btn btn-primary mt-4" type="submit" value="契約を確定する">
              </div>
            <% elsif @agreement.agreement_flag != true && @agreement.pilot_id == current_user.id %>
              <p>契約が未確定です。ユーザーが契約内容に同意すると契約が確定します。</p>
            <% end %>
          <% end %>
        </dl>
      </div>
    </div>
  </div>
</main>