config/routes.rb
Rails.application.routes.draw do


  get 'users/:id/show' => "users#show"
  post 'comments/:id/create' => "comments#create"
  post 'comments/:id/destroy' => "comments#destroy"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :charges
  resources :agreements, :only => [:create]
  resources :messages, :only => [:create, :destroy]
  resources :rooms, :only => [:create, :destroy, :show]
  
  get '/' => "home#top"
  get '/about' => "home#about"
  get '/terms' => "home#terms"
  get '/privacy' => "home#privacy"
  get '/flow' => "home#flow"
  get '/ctl' => "home#ctl"
  get '/contact' => "home#contact"
  get '/signup' => "home#signup"
  get '/mypage' => "home#mypage"


  get 'movies/index' => "movies#index"
  get 'movies/:id/show' => "movies#show"
  get 'movies/wedding_more' => "movies#wedding_more"
  get 'movies/travel_more' => "movies#travel_more"
  get 'movies/anniversary_more' => "movies#anniversary_more"
  get 'movies/other_more' => "movies#other_more"
  get 'movies/new' => "movies#new"
  get 'movies/:id/new' => "movies#new2"
  post 'movies/create' => "movies#create"

  get 'pilots/index' => "pilots#index"
  get 'pilots/:id/show' => "pilots#show"
  get 'pilots/offer' => "pilots#offer"
  get 'pilots/reservation' => "pilots#reservation"
  get 'pilots/ace_more' => "pilots#ace_more"
  get 'pilots/pro_more' => "pilots#pro_more"
  get 'pilots/amature_more' => "pilots#amature_more"
  get 'pilots/new' => "pilots#new"
  post 'pilots/create' => "pilots#create"
  
  get 'agreements/:id/new' => "agreements#new"  
  get 'agreements/:id/show' => "agreements#show"
  post 'agreements/:id/agree' => "agreements#agree"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    elsif user
      can :read, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/agreement.rb
class Agreement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title,{presence: true}
  validates :user_id,{presence: true}
  validates :pilot_id,{presence: true}
  validates :url,{presence: true}
  validates :tag,{presence: true}
  belongs_to :user
  belongs_to :pilot
  has_many :comments
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  validates :user_id,{presence: true, uniqueness: true}
  validates :name,{presence: true}
  validates :rank,{presence: true}
  validates :adress,{presence: true}
  validates :skill,{presence: true}
  validates :tools,{presence: true}
  validates :price,{presence: true}
  validates :insuarance,{presence: true}
  validates :message,{presence: true}
  belongs_to :user
  has_many :movies
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :pilots, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :agreements, dependent: :destroy
  include Gravtastic
    gravtastic
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
  def terms
  end
  def privacy
  end
  def ctl
  end
  def flow
  end
  def contact
  end
  def mypage
    @entries = Entry.where(user: current_user.id)
    @agreements_u = Agreement.where(user_id: current_user.id)
    @agreements_p = Agreement.where(pilot_id: current_user.id)
  end
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
    <!-- footer -->
    <footer>
      <div class="footer-left">
        <div class="copy-right">
          <p>&copy HOWDY DRONE All rights reserved.</p>
        </div>
      </div>
      <div class="footer-right hidden-xs">
        <li><a href="/terms">利用規約</a></li>
        <li><a href="/privacy">プライバシーポリシー</a></li>
        <li><a href="/flow">ご利用までの流れ</a></li>
        <li><a href="/contact">お問い合わせ</a></li>
      </div>
    </footer>

app/views/layouts/_in-navbar.html.erb
    <header>
      <div class="header-left">
        <a href="/"><img src="/drone-w.png" alt="" width="28px">HOWDY DRONE</a>
      </div>
      <div class="header-right">
        <a href="/users/sign_in"><p id="modal-open">ログイン</p></a> <!--ログイン前-->
        <img id="menu-modal-open" src="/menu-w.png" alt="" width="28px;">
      </div>
    </header>

app/views/layouts/_out-navbar.html.erb
    <header>
      <div class="header-left">
        <a href="/"><img src="/drone-w.png" alt="" width="28px">HOWDY DRONE</a>
      </div>
      <div class="header-right">
        <a href="/mypage"><p id="modal-open">マイページ</p></a> <!--ログイン前-->
        <img id="menu-modal-open" src="/menu-w.png" alt="" width="28px;">
      </div>
    </header>
    
    

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja"> <!--言語設定-->
  <head>
    <meta charset="utf-8">  <!-- 文字コード -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  <!-- レスポンシブ 576px:sm  768px:md  992px:lg  1200px:xl -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> <!-- Bootstrap CSS -->
    <title></title> <!--タイトル-->
    <link rel="icon" href="/"> <!--タブアイコン-->
    <link href="https://fonts.googleapis.com/css?family=Vampiro+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"> <!--font-awsome読み込み-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%> <!--css読み込み-->
    <%= javascript_include_tag 'application'%>  <!--js読み込み-->
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <%= yield %>

    <!-- header -->
      <% if user_signed_in? %>
        <%= render 'layouts/out-navbar' %>　<!--ログイン後-->
      <% else %>
        <%= render 'layouts/in-navbar' %>　　<!--ログイン前-->
      <% end %>
      
          
    <!-- footer -->
    <footer>
      <div class="footer-left">
        <div class="copy-right">
          <p>&copy HOWDY DRONE All rights reserved.</p>
        </div>
      </div>
      <div class="footer-right hidden-xs">
        <li><a href="/terms">利用規約</a></li>
        <li><a href="/flow">ご利用までの流れ</a></li>
        <li><a href="/ctl">特定商取引法に基づく表示</a></li>
        <li><a href="/privacy">プライバシーポリシー</a></li>
        <li><a href="/contact">お問い合わせ</a></li>
      </div>
    </footer>

      <!-- menuモーダルウインドウ -->
      <div id="menu-modal-main">
        <div class="container text-center">
          
          <% if user_signed_in? %>
            <a href="/mypage">マイページ</a>
          <% else %>
            <a href="/">トップページ</a>
          <% end %>
          <a href="/movies/index">投稿一覧</a>
          <% if can? :update, movies_new_url %>
            <a href="/movies/new">動画投稿</a>
          <% end %>
          <!--<a href="/pilots/index">パイロット一覧</a>-->
          <% if can? :update, pilots_new_url %>
            <a href="/pilots/new">パイロット登録</a>
          <% end %>
          <a href="/terms">利用規約</a>
          <a href="/flow">ご利用までの流れ</a>
          <a href="/ctl">特定商取引法に基づく表示</a>
          <a href="/privacy">プライバシーポリシー</a>
          <a href="/contact">お問い合わせ</a>
          <% if user_signed_in? %>
            <a><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %> <!--ログイン後--></a>
          <% end %>
        </div>
        <div id="menu-modal-close">
          <img src="/close.png" alt="" width="30px">
        </div>
      </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> <!--jQuery読み込み-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>  <!--bootstrap読み込み-->
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      <!--
        main{
          margin:100px auto;
          text-align:center;
        }
        h2{
          display:inline-block;
          margin:0 auto;
          font-size:20px;
          width:300px;
          background:rgba(158,158,158,0.3);
          padding:20px 0;
          font-weight:normal;
          margin-bottom:30px;
        }
        h3{
          font-weight:normal;
          font-size:1vw;
          margin-bottom:70px;
        }
        h4{
          font-weight:normal;
          font-size:2vw;
        }
        .amount-confirm{
          margin:0 auto;
          width:380px;
          background:rgba(158,158,158,0.1);
          padding:20px 0;
        }
        span{
          font-weight:bold;
        }
        p{
          margin-top:70px;
          margin-bottom:50px;
          font-size:0.9vw;
          opacity:0.8;
        }
        .top-link a{
          display:block;
          color:black;
          font-size:1.0vw;
          /*text-decoration:none;*/
          margin-bottom:30px;
        }
        .top-link a:hover{
          opacity:0.7;
        }
      -->
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>